export interface GlossarEntry {
  term: string;
  definition: string;
}

export const GLOSSAR: GlossarEntry[] = [
  { term: "Aktie", definition: "Anteilsschein, der den Inhaber zum Miteigentümer eines Unternehmens macht." },
  { term: "Aktienindex", definition: "Kennzahl, die die Kursentwicklung vieler Aktien bündelt (z. B. DAX, S&P 500)." },
  { term: "Anleihe", definition: "Verzinstes Wertpapier; der Käufer gibt dem Emittenten einen Kredit (Fremdkapital)." },
  { term: "Ausschüttungsquote", definition: "Anteil des Gewinns, der als Dividende ausgezahlt wird (Payout Ratio)." },
  { term: "Bilanz", definition: "Stichtagsübersicht von Vermögen (Aktiva) und dessen Finanzierung (Passiva)." },
  { term: "Burggraben", definition: "Nachhaltiger Wettbewerbsvorteil, der Gewinne vor Konkurrenz schützt (Economic Moat)." },
  { term: "Candlestick", definition: "Kerzen-Chartdarstellung von Open, High, Low und Close je Zeitraum." },
  { term: "Cashflow", definition: "Tatsächlicher Geldzu- und -abfluss eines Unternehmens in einem Zeitraum." },
  { term: "Cost-Average-Effekt", definition: "Bei festem Sparbetrag werden bei tiefen Kursen mehr Anteile gekauft als bei hohen." },
  { term: "Diversifikation", definition: "Verteilung des Kapitals auf viele Anlagen zur Risikostreuung." },
  { term: "Dividende", definition: "Ausschüttung eines Teils des Unternehmensgewinns an die Aktionäre." },
  { term: "Dividendenrendite", definition: "Jährliche Dividende je Aktie im Verhältnis zum Aktienkurs." },
  { term: "EBIT", definition: "Gewinn vor Zinsen und Steuern; Maß der operativen Ertragskraft." },
  { term: "EBITDA", definition: "EBIT zuzüglich Abschreibungen; grobe Näherung, aber kein echter Cashflow." },
  { term: "ETF", definition: "Börsengehandelter Fonds, der einen Index kostengünstig nachbildet." },
  { term: "Free Cashflow", definition: "Operativer Cashflow abzüglich der nötigen Investitionen (Capex)." },
  { term: "Fundamentalanalyse", definition: "Bewertung eines Unternehmens anhand von Zahlen und Geschäftsmodell." },
  { term: "Gesamtrendite", definition: "Summe aus Kursveränderung und erhaltenen Dividenden (Total Return)." },
  { term: "Gleitender Durchschnitt", definition: "Geglätteter Durchschnittskurs der letzten n Tage (SMA/EMA)." },
  { term: "Golden Cross", definition: "Kurzfristiger Durchschnitt kreuzt den langfristigen von unten nach oben (bullisch)." },
  { term: "GuV", definition: "Gewinn- und Verlustrechnung: Umsatz, Kosten und Gewinn über einen Zeitraum." },
  { term: "Inflation", definition: "Allgemeiner Anstieg des Preisniveaus; Geld verliert an Kaufkraft." },
  { term: "KBV", definition: "Kurs-Buchwert-Verhältnis: Kurs geteilt durch bilanzielles Eigenkapital je Aktie." },
  { term: "KGV", definition: "Kurs-Gewinn-Verhältnis: Kurs geteilt durch Gewinn je Aktie." },
  { term: "KUV", definition: "Kurs-Umsatz-Verhältnis: Kurs geteilt durch Umsatz je Aktie." },
  { term: "Limit-Order", definition: "Order mit Höchstpreis (Kauf) bzw. Mindestpreis (Verkauf); Preiskontrolle statt Ausführungsgarantie." },
  { term: "Liquidität", definition: "Wie leicht ein Wert ohne starke Kursbewegung gehandelt werden kann." },
  { term: "MACD", definition: "Indikator aus dem Abstand zweier EMAs (meist 12/26) plus Signallinie." },
  { term: "Market-Order", definition: "Order zur sofortigen Ausführung zum besten verfügbaren Preis." },
  { term: "Marktkapitalisierung", definition: "Börsenwert eines Unternehmens: Kurs mal Anzahl der Aktien." },
  { term: "Ordergebühr", definition: "Kosten des Brokers für die Ausführung eines Kauf- oder Verkaufsauftrags." },
  { term: "Realrendite", definition: "Rendite nach Abzug der Inflation; der echte Kaufkraftgewinn." },
  { term: "RSI", definition: "Relative Strength Index (0–100); misst überkaufte bzw. überverkaufte Lagen." },
  { term: "Sparer-Pauschbetrag", definition: "Jährlicher Steuerfreibetrag für Kapitalerträge (1.000 € pro Person)." },
  { term: "Sparplan", definition: "Automatisierte, regelmäßige Investition eines festen Betrags." },
  { term: "Spread", definition: "Differenz zwischen Geldkurs (Bid) und Briefkurs (Ask)." },
  { term: "Stop-Loss", definition: "Order, die bei Erreichen einer Kursmarke automatisch verkauft, um Verluste zu begrenzen." },
  { term: "Support & Resistance", definition: "Kurszonen mit historisch starkem Kauf- (Support) bzw. Verkaufsdruck (Resistance)." },
  { term: "TER", definition: "Total Expense Ratio: laufende Gesamtkostenquote eines Fonds oder ETFs." },
  { term: "Volatilität", definition: "Maß für die Schwankungsbreite eines Kurses; ein Indikator für Risiko." },
  { term: "Volumen", definition: "Anzahl der in einem Zeitraum gehandelten Aktien; misst die Marktbeteiligung." },
];
